// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwboNNxRxwMBf04zCHSZZgAj7FwWDR3to',
    appId: '1:881856744204:web:f6cd4217fc8417041f5729',
    messagingSenderId: '881856744204',
    projectId: 'store-app-a25b8',
    authDomain: 'store-app-a25b8.firebaseapp.com',
    storageBucket: 'store-app-a25b8.firebasestorage.app',
    measurementId: 'G-02E5KB0JML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1s5YaWiJNmqv776ivKKk2A8eatLiw7Fg',
    appId: '1:881856744204:android:e1c61c8d43675af61f5729',
    messagingSenderId: '881856744204',
    projectId: 'store-app-a25b8',
    storageBucket: 'store-app-a25b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv3HLXVPte9R9sCY6Hx-ASJSnflM-2O4Y',
    appId: '1:881856744204:ios:bdae5c39b2bc569e1f5729',
    messagingSenderId: '881856744204',
    projectId: 'store-app-a25b8',
    storageBucket: 'store-app-a25b8.firebasestorage.app',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv3HLXVPte9R9sCY6Hx-ASJSnflM-2O4Y',
    appId: '1:881856744204:ios:bdae5c39b2bc569e1f5729',
    messagingSenderId: '881856744204',
    projectId: 'store-app-a25b8',
    storageBucket: 'store-app-a25b8.firebasestorage.app',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwboNNxRxwMBf04zCHSZZgAj7FwWDR3to',
    appId: '1:881856744204:web:85089c701d187f4d1f5729',
    messagingSenderId: '881856744204',
    projectId: 'store-app-a25b8',
    authDomain: 'store-app-a25b8.firebaseapp.com',
    storageBucket: 'store-app-a25b8.firebasestorage.app',
    measurementId: 'G-DW4MZRHM5N',
  );
}
